package com.leadlens.briefing.model;

import java.time.Instant;

/**
 * The result of a {@link com.leadlens.crm.CrmNarrativeSource} call: prose generated by a CRM's
 * own AI engine over its own records, distinct from anything LeadLens extracted itself.
 *
 * @param text        the narrative, rendered verbatim (F.3) - never reworded downstream
 * @param model       the model that produced it, for the citation the panel shows
 * @param generatedAt when the source generated it (not when LeadLens received it)
 * @param sourceLabel human-readable description of what was queried, e.g. "CRM AI - Lead 4521,
 *                    Project 88"
 */
public record CrmNarrative(String text, String model, Instant generatedAt, String sourceLabel) {
}
